//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveReceipt
    {
        public int approveReceiptId { get; set; }
        public Nullable<int> marketId { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public Nullable<int> depositType { get; set; }
    }
}
