//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuthenticationEntities : DbContext
    {
        public AuthenticationEntities()
            : base("name=AuthenticationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessLevel> AccessLevels { get; set; }
        public DbSet<ActionMethod> ActionMethods { get; set; }
        public DbSet<Grant> Grants { get; set; }
        public DbSet<ParentFacility> ParentFacilities { get; set; }
        public DbSet<ParentFacilityRole> ParentFacilityRoles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SubFacility> SubFacilities { get; set; }
        public DbSet<SubFacilityRole> SubFacilityRoles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<LogIn> LogIns { get; set; }
    }
}
