//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bankDeposit
    {
        public int id { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> ApproveReceiptFK { get; set; }
    }
}
