//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDeliveryRequest
    {
        public int DeliveryId { get; set; }
        public long DeliveryNo { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    }
}
