//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookType
    {
        public int BookTypeId { get; set; }
        public int BookNo { get; set; }
        public int RecTypeId { get; set; }
        public int LicenseId { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
