//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookResposibility
    {
        public int RespId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> HandleBookReceiptId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> PartialBookIndicator { get; set; }
        public Nullable<int> ParentEmployeeId { get; set; }
        public Nullable<int> NextReceiptNo { get; set; }
        public Nullable<int> DoneFlag { get; set; }
        public Nullable<long> RequestNo { get; set; }
    }
}
