//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRequest
    {
        public int id { get; set; }
        public Nullable<int> employeeFK { get; set; }
        public Nullable<int> bookTypefk { get; set; }
        public Nullable<int> numberrequests { get; set; }
    }
}
