//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanceledReceipt
    {
        public int CanceledReceiptId { get; set; }
        public Nullable<int> ResponsibilityId { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<int> Canceled { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
    }
}
