//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class doner
    {
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string numberOfDonations { get; set; }
        public Nullable<int> DID { get; set; }
        public string address { get; set; }
        public string wasf { get; set; }
        public Nullable<int> cent_id { get; set; }
        public string job { get; set; }
        public string workplace { get; set; }
        public string sex { get; set; }
        public string @class { get; set; }
        public string Typecontact { get; set; }
        public string motabare3 { get; set; }
        public string freq { get; set; }
        public string email { get; set; }
        public string notes { get; set; }
        public string mob { get; set; }
        public Nullable<int> site { get; set; }
        public Nullable<int> NULL { get; set; }
        public Nullable<int> DonorOfId { get; set; }
        public Nullable<int> DonationFreqId { get; set; }
    
        public virtual center center { get; set; }
    }
}
