//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grant
    {
        public int UserId { get; set; }
        public int ActionMethodId { get; set; }
        public int AccessLevel { get; set; }
    
        public virtual AccessLevel AccessLevel1 { get; set; }
        public virtual ActionMethod ActionMethod { get; set; }
        public virtual LogIn LogIn { get; set; }
    }
}
