//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketingsite
    {
        public marketingsite()
        {
            this.markets = new HashSet<market>();
        }
    
        public int id { get; set; }
        public string sitename { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual ICollection<market> markets { get; set; }
    }
}
