//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class market
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dat { get; set; }
        public int no { get; set; }
        public string cod { get; set; }
        public Nullable<int> name { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string currency { get; set; }
        public Nullable<int> cash { get; set; }
        public Nullable<int> employee { get; set; }
        public Nullable<int> type { get; set; }
        public string note { get; set; }
        public Nullable<int> site { get; set; }
        public string combID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string FinApprov { get; set; }
        public Nullable<int> ResponsibilityId { get; set; }
        public Nullable<int> DonationPurposeId { get; set; }
        public Nullable<int> ChequeInfoId { get; set; }
    
        public virtual marketingsite marketingsite { get; set; }
    }
}
