//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentFacility
    {
        public ParentFacility()
        {
            this.ParentFacilityRoles = new HashSet<ParentFacilityRole>();
            this.SubFacilities = new HashSet<SubFacility>();
        }
    
        public int ParentId { get; set; }
        public string ParentFacilityArabicName { get; set; }
        public string ParentFacilityEnglishName { get; set; }
        public string ClassNames { get; set; }
    
        public virtual ICollection<ParentFacilityRole> ParentFacilityRoles { get; set; }
        public virtual ICollection<SubFacility> SubFacilities { get; set; }
    }
}
