//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentFacilityRole
    {
        public int FacilityRoleId { get; set; }
        public int ParentFacilityId { get; set; }
        public int RoleId { get; set; }
    
        public virtual ParentFacility ParentFacility { get; set; }
        public virtual Role Role { get; set; }
    }
}
