//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.ParentFacilityRoles = new HashSet<ParentFacilityRole>();
            this.SubFacilityRoles = new HashSet<SubFacilityRole>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleEnglishName { get; set; }
        public string RoleArabicName { get; set; }
        public string RoleDescription { get; set; }
        public string Comments { get; set; }
        public bool IsSystemGenerated { get; set; }
    
        public virtual ICollection<ParentFacilityRole> ParentFacilityRoles { get; set; }
        public virtual ICollection<SubFacilityRole> SubFacilityRoles { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
