//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFacility
    {
        public SubFacility()
        {
            this.SubFacilityRoles = new HashSet<SubFacilityRole>();
        }
    
        public int Id { get; set; }
        public string FacilityEnglishName { get; set; }
        public string FacilityArabicName { get; set; }
        public Nullable<int> ParentFacilityId { get; set; }
        public string URL { get; set; }
        public string CssClasses { get; set; }
    
        public virtual ParentFacility ParentFacility { get; set; }
        public virtual ICollection<SubFacilityRole> SubFacilityRoles { get; set; }
    }
}
