//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECBNewWeb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string volunteer_id { get; set; }
        public Nullable<short> passChanged { get; set; }
        public Nullable<int> department { get; set; }
        
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserComments { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<short> IsResetPasswordNeeded { get; set; }
        public Nullable<System.DateTime> PasswordChangedOn { get; set; }
        public string SecurityQuestionID { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<int> userRole { get; set; }
        public Nullable<int> importance { get; set; }
        public Nullable<short> active { get; set; }
    }
}
